/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleContent: typeof import('./src/components/Article/ArticleContent.vue')['default']
    ArticleLink: typeof import('./src/components/Article/ArticleLink.vue')['default']
    ArticleQuote: typeof import('./src/components/Article/ArticleQuote.vue')['default']
    ArticleSingleImage: typeof import('./src/components/Article/ArticleSingleImage.vue')['default']
    ArticleSubtitle: typeof import('./src/components/Article/ArticleSubtitle.vue')['default']
    ArticleTitle: typeof import('./src/components/Article/ArticleTitle.vue')['default']
    ExperienceCard: typeof import('./src/components/ExperienceCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
